# -*- coding: utf-8 -*-
"""parser.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XykSyXuP_zqAhDnKaK-Xussth8W2gYc9
"""

#We will use stream lit to turn out data script into webapp before deployment to Heroku
#Should on the same dir as the Machine Learning model

import streamlit as st
import pickle
import pandas as pd

def recommend(movie):
    if movie not in movies['title'].values:
        print(f"Sorry, the movie '{movie}' is not in our database.")
        return

    #Borrowed from the ML model
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    recommended_movies = []

    for i in movie_list:
        recommended_movies.append(movies.iloc[i[0]].title)
    return recommended_movies

#We pickled the last steps of the ML model and saved this files this way
movies_dict = pickle.load(open('movies_dict.pkl', 'rb'))
movies = pd.DataFrame(movies_dict)
similarity = pickle.load(open('similarity.pkl', 'rb'))
st.title("Movie Recommender system")
option = st.selectbox('Select your Movie:', movies['title'].values)

if st.button('Recommend'):
  recommendations = recommend(option)
  for i in recommendations:
    st.write(i)

#Running the streamlit app --> streamlit run app.py